import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Oxanium } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Header from "./components/Header";
import MobileHeader from "./components/MobileHeader";
import PageLoading from "./components/PageLoading";
import PreLoader from "./components/PreLoader";
import Noise from "./components/Noise";
import "./globals.css";

const oxanium = Oxanium({
  subsets: ['latin'],
  display: 'swap',
  preload: true,
  weight: '200',
  variable: '--font-oxanium',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${oxanium.className} antialiased relative min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          storageKey="theme-preference"
          enableSystem={false}
        >
          <div className="relative z-0">
            <Noise
              patternSize={250}
              patternScaleX={1}
              patternScaleY={1}
              patternRefreshInterval={2}
              patternAlpha={10}
            />
          </div>
          <div className="relative z-10">
            <PreLoader />
            <div className="contents">
              <PageLoading />
              <div className="hidden md:block">
                <Header />
              </div>
              <div className="md:hidden">
                <MobileHeader />
              </div>
              <main className="pt-[calc(2.5rem+10px-90px)] md:pt-0 pb-24 md:py-0">
        {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
